Revert "fix: warning: multi-character character constant"
This reverts commit b1cde001e6201b77e77e3da69380d50f6a0a4165.

fix:

./CoreAudio/CoreAudioTypes.h:348:44: error: ‘reinterpret_cast’ is not a constant expression
  348 |     kAudioFormatLinearPCM               = *(int32_t*)"lpcm",
      |                                            ^~~~~~~~~~~~~~~~